### ISSUE TITLE
При использовании bundles происходит ошибка

### ISSUE THREAD

**Issue by budarin** [Kuznetsov-Ilia/gulp-lmd#2]
Пытаюсь собрать проект с bundles
При сборке его при помощи командной строки - все происходит нормально и проект грузится нормально и зависимости подгружаются правильно
При использовании плагина - плагин не генерирует бандлы вообще

**Comment by Kuznetsov-Ilia** [comment]
Привет. Lmd уже пару лет как заброшен автором, но я попробую разобраться, если ты предоставишь конкретный конфиг галп таска и lmd.
